site_name: django-whiteless
site_url: https://django-whiteless.readthedocs.io/en/latest/
repo_url: https://github.com/denizdogan/django-whiteless
site_author: Deniz Dogan
markdown_extensions:
    - smarty
    - fenced_code
    - codehilite
    - markdown_include.include
extra_css: [codehilite.css]
